### ISSUE TITLE
android jetifier transfer android support aar to androidx aar failed 

### ISSUE THREAD

**Issue by mtcle** [JetBrains/intellij-deps-asm#6]
I have an Android library that was originally written using Android Support and is intended for integration with AndroidX. Everything works fine when my AAR library is not obfuscated. However, when I obfuscate the AAR and then attempt to convert it to AndroidX in Android Studio, I encounter the following error

➜  bin ./jetifier-standalone -i sdk.aar -o ./        
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -2
	at java.lang.String.substring(String.java:1967)
	at org.objectweb.asm.signature.SignatureReader.parseType(SignatureReader.java:178)
	at org.objectweb.asm.signature.SignatureReader.acceptType(SignatureReader.java:140)
	at org.objectweb.asm.commons.Remapper.mapSignature(Remapper.java:207)
	at org.objectweb.asm.commons.ClassRemapper.visitField(ClassRemapper.java:171)
	at org.objectweb.asm.ClassReader.readField(ClassReader.java:1111)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:713)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:401)
	at com.android.tools.build.jetifier.processor.transform.bytecode.ByteCodeTransformer.runTransform(ByteCodeTransformer.kt:40)
	at com.android.tools.build.jetifier.processor.Processor.visit(Processor.kt:592)
	at com.android.tools.build.jetifier.processor.archive.ArchiveFile.accept(ArchiveFile.kt:59)
	at com.android.tools.build.jetifier.processor.Processor.visit(Processor.kt:574)
	at com.android.tools.build.jetifier.processor.archive.Archive.accept(Archive.kt:78)
	at com.android.tools.build.jetifier.processor.Processor.visit(Processor.kt:574)
	at com.android.tools.build.jetifier.processor.archive.Archive.accept(Archive.kt:78)
	at com.android.tools.build.jetifier.processor.Processor.transformLibrary(Processor.kt:570)
	at com.android.tools.build.jetifier.processor.Processor.transform2(Processor.kt:335)
	at com.android.tools.build.jetifier.processor.Processor.transform2$default(Processor.kt:295)
	at com.android.tools.build.jetifier.standalone.Main.run(Main.kt:181)
	at com.android.tools.build.jetifier.standalone.Main$Companion.main(Main.kt:119)
	at com.android.tools.build.jetifier.standalone.Main.main(Main.kt)

**Comment by trespasserw** [comment]
This ASM fork has the package `org.jetbrains.org.objectweb.asm`. It is not the ~~droid you're looking for~~ library that Android build tools use.
